// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUip4sNMBtnoDcZ_vDPJksfjqtVRMajik',
    appId: '1:652526809652:web:2a73d370ab18f156ccd061',
    messagingSenderId: '652526809652',
    projectId: 'auth-app-f8772',
    authDomain: 'auth-app-f8772.firebaseapp.com',
    storageBucket: 'auth-app-f8772.appspot.com',
    measurementId: 'G-KVWYNVXKF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGaLPFEATG8LZF4Wkg5ZyMbzbKActSK8',
    appId: '1:652526809652:android:f3733f8aef98a765ccd061',
    messagingSenderId: '652526809652',
    projectId: 'auth-app-f8772',
    storageBucket: 'auth-app-f8772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIwjqEiJQ7Y0XYmoL4oNw4ERoz2qb65Q',
    appId: '1:652526809652:ios:d9ac362dc446900accd061',
    messagingSenderId: '652526809652',
    projectId: 'auth-app-f8772',
    storageBucket: 'auth-app-f8772.appspot.com',
    iosBundleId: 'com.example.authAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIwjqEiJQ7Y0XYmoL4oNw4ERoz2qb65Q',
    appId: '1:652526809652:ios:f43be26d50658096ccd061',
    messagingSenderId: '652526809652',
    projectId: 'auth-app-f8772',
    storageBucket: 'auth-app-f8772.appspot.com',
    iosBundleId: 'com.example.authAppFirebase.RunnerTests',
  );
}
